
import type { Metadata } from "next";
import localFont from "next/font/local";
// import Providers from './components/providers';
import "./globals.css";
// import { AnonAadhaarProvider } from "@anon-aadhaar/react";
// import { LogProvider } from "./providers/LogContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "StakerDeck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* <Providers> */}
         {/* <AnonAadhaarProvider _useTestAadhaar={true}> */}
         {/* <LogProvider> */}
          {children}
          {/* </LogProvider> */}
          {/* </AnonAadhaarProvider> */}
          {/* </Providers> */}
      </body>
    </html>
    
  );
}
